services:
  - type: web
    name: ottawa-ndzibs-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /api/services